apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rajureddy-ingress
  namespace: purely
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Optional: Enable automatic HTTPS via cert-manager (if installed)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: purely.rajureddy.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc      
            port:
              number: 80

  - host: purelyapi.rajureddy.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway-svc       
            port:
              number: 8080
