apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: rajureddy98/purely-order-service:1.0
          ports:
            - containerPort: 9070
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-DCONFIG_SERVER_URI=configserver:http://config-server:8888 -Dspring.profiles.active=k8s"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 9070
      targetPort: 9070
      protocol: TCP
